config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

  resources :posts do
   resources :comments
  end

  resources :users, only: [] do
    resources :posts, controller: "user_posts"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, length: {minimum: 4, maximum: 30}
  validates :user_name, uniqueness: true
  validates :email, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  attr_accessor :login

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    p devise_parameter_sanitizer
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :destroy, :show, :update]

  def index
    @post = Post.new if user_signed_in?
    @posts = Post.all
    @posts = @posts.sort_by {|post| post.created_at}.reverse
    # if params[:user_id]

      # user = User.find(params[:user_id])
      # @posts = user.posts
    # else
      # @posts = Post.all
    # end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    new_post = Post.create(post_params)
    redirect_to(posts_url)
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to(@post)
  end

  def destroy
    @post.destroy
    redirect_to(posts_url)
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :content)
  end

end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<% if user_signed_in? %>
  <div class="logout-button">
    <%= button_to "Logout", destroy_user_session_path, method: :delete %>
  </div>
<%end%>
</body>
</html>

app/views/posts/_form.erb
<div class='new-post'>
  <%= form_for(@post) do |f| %>
    <%= f.text_field :content %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/index.erb
<div>
  <% if current_user %>
    <h3>
      <%= link_to "Share your terrible, trivial musings", new_post_path %>
    </h3>
    <%= render 'form' %>
  <%else%>
    <h3>
      <%= link_to "Sign up to post your own pointless thoughts", new_user_session_url %>
    </h3>
  <%end%>
</div>


<div class="posts">
  <% @posts.each do |post| %>
    <div class="post" id="post-<%=post.id%>">
      <%= post.content %>
      <br/>
      (<%=post.comments.count%> comments)
      <br/>
      <p>Posted by
        <%= link_to post.user.user_name, user_posts_path(post.user) %> <%= post.created_at.strftime("at %H:%M on %d/%m/%Y") %>
      </p>

      <p><%= link_to "More", post %> </p>

      <% if post.user.id == current_user.id %>
        <%= button_to "Delete", post, method: :delete %>
      <% end %>


    </div>

  <%end%>

</div>

app/views/posts/new.erb
<%= render 'form' %>

app/views/posts/show.erb
<div class="individual-post">
  <%=@post.id%><br/>
  <%=@post.content%><br/>
  <%=@post.user.user_name%><br/>

  <div class="comments-container">
    <%@post.comments.each do |comment| %>
      <div class="comment">
        <%=comment.content%> <br/>
        -Comment posted by <%=comment.user.user_name%>
        <%= comment.created_at.strftime("at %H:%M%p on %d/%m/%Y") %>
        <br/>
      </div>
    <%end%>
  </div>

</div>

app/views/welcome/index.html.erb
<h1>JamMan</h1>


<% if current_user %>
<h3>Good to see you, <%= current_user.user_name %></h3>
  <%= link_to "Check out the scene", posts_path %>
<% else %>
  <h3>What do you wanna do?</h3>
  <%= button_to "Sign Up", new_user_registration_path, method: :get %>
  <%= button_to "Log In", new_user_session_path, method: :get %>
  <%= link_to "Check it out", posts_path %>
<% end %>